config/routes.rb
ChromeExtensionUpdateCenter::Application.routes.draw do
  resources :extensions do
    collection do
      get '/updates.xml' => 'extensions#updates', format: :xml
    end

    member do
      get '/crx' => 'extensions#crx'
    end
  end

  root :to => redirect('/extensions')
end

app/models/extension.rb
require 'tmpdir'
require 'json'

class Extension < ActiveRecord::Base
  attr_accessible :appid, :crx, :name, :pem, :release, :version

  validates :name, presence: true
  validates :appid, presence: true
  validates :version, presence: true, uniqueness: { scope: :appid }
  validates :crx, presence: true

  def store_binary_data
    self.crx = crx.read if crx
    self.pem = pem.read if pem
  end

  def unpack_crx
    return unless crx
    Dir.mktmpdir do |tmpdir|
      CrxUnpack.unpack_contents(crx.dup, tmpdir)
      manifest = JSON.parse(open(File.join(tmpdir, 'manifest.json')).read)
      self.name = manifest['name']
      self.version = manifest['version']
    end
  rescue => e
    Rails.logger.error("#{e.class} #{e.message}")
    self.errors.add(:crx, "Invalid crx format")
  end

  def calculate_appid
    return unless pem
    self.appid = CrxAppid.calculate(pem)
  rescue => e
    Rails.logger.error("#{e.class} #{e.message}")
    self.errors.add(:pem, "Invalid pem format")
  end

  def self.latest_versions
    self.pluck(:appid).uniq.map{ |appid|
      self.where(appid: appid, release: true).order('version DESC').first
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/extensions_controller.rb
class ExtensionsController < ApplicationController
  respond_to :html, :json

  def index
    @extensions = Extension.all
    respond_with @extensions
  end

  def show
    @extension = Extension.find(params[:id])
    respond_with @extension
  end

  def new
    @extension = Extension.new
    respond_with @extension
  end

  def edit
    @extension = Extension.find(params[:id])
  end

  def create
    @extension = Extension.new(params[:extension])
    @extension.store_binary_data
    @extension.unpack_crx
    @extension.calculate_appid

    respond_to do |format|
      if @extension.save
        format.html { redirect_to @extension, notice: 'Extension was successfully created.' }
        format.json { render json: @extension, status: :created, location: @extension }
      else
        format.html { render action: "new" }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @extension = Extension.find(params[:id])

    respond_to do |format|
      if @extension.update_attributes(params[:extension])
        format.html { redirect_to @extension, notice: 'Extension was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @extension.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @extension = Extension.find(params[:id])
    @extension.destroy

    respond_to do |format|
      format.html { redirect_to extensions_url }
      format.json { head :no_content }
    end
  end

  def updates
    @extensions = Extension.latest_versions
    respond_to do |format|
      format.xml { render }
    end
  end

  def crx
    extension = Extension.find(params[:id])

    if extension.version != params[:v]
      render text: "Invalid version parameter", status: 403
    end

    send_data extension.crx, type: 'application/x-chrome-extension', filename: extension.appid + ".crx", disposition: :inline
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extensions_helper.rb
module ExtensionsHelper
end

app/views/extensions/_form.html.erb
<%= form_for(@extension, html: {multipart: true})  do |f| %>
  <% if @extension.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@extension.errors.count, "error") %> prohibited this extension from being saved:</h2>

      <ul>
      <% @extension.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% unless @extension.new_record? %>
    <div class="field">
      <%= label_tag :name %><br />
      <%= label_tag @extension.name %>
    </div>
    <div class="field">
      <%= label_tag :appid %><br />
      <%= label_tag @extension.appid %>
    </div>
  <% end %>

  <% if @extension.new_record? %>
    <div class="field">
      <%= f.label :crx %><br />
      <%= f.file_field :crx %>
    </div>
    <div class="field">
      <%= f.label :pem %><br />
      <%= f.file_field :pem %>
    </div>
    <div class="field">
      <%= f.label :appid %><br />
      <%= f.text_field :appid %>
    </div>
  <% end %>

  <% unless @extension.new_record? %>
    <div class="field">
      <%= label_tag :version %><br />
      <%= label_tag @extension.version %>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :release %><br />
    <%= f.check_box :release %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/extensions/edit.html.erb
<h1>Editing extension</h1>

<%= render 'form' %>

<%= link_to 'Show', @extension %> |
<%= link_to 'Back', extensions_path %>

app/views/extensions/index.html.erb
<h1>Listing extensions</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Appid</th>
    <th>Version</th>
    <th>Release</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @extensions.each do |extension| %>
  <tr>
    <td><%= extension.name %></td>
    <td><%= extension.appid %></td>
    <td><%= extension.version %></td>
    <td><%= extension.release %></td>
    <td><%= link_to 'Show', extension %></td>
    <td><%= link_to 'Edit', edit_extension_path(extension) %></td>
    <td><%= link_to 'Destroy', extension, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Extension', new_extension_path %>

app/views/extensions/new.html.erb
<h1>New extension</h1>

<%= render 'form' %>

<%= link_to 'Back', extensions_path %>

app/views/extensions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @extension.name %>
</p>

<p>
  <b>Appid:</b>
  <%= @extension.appid %>
</p>

<p>
  <b>Version:</b>
  <%= @extension.version %>
</p>

<p>
  <b>Release:</b>
  <%= @extension.release %>
</p>


<%= link_to 'Edit', edit_extension_path(@extension) %> |
<%= link_to 'Back', extensions_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChromeExtensionUpdateCenter</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>